### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by taospartan** [LCAV/easy-dsp#10]
On running make the following error is generated

`gcc -g -Wall -Wextra -O0 -std=gnu99 browser-main-daemon.c -o browser-main-daemon -lasound -lpthread
browser-main-daemon.c: In function ‘main’:
browser-main-daemon.c:74:3: warning: implicit declaration of function ‘query_available_config’ [-Wimplicit-function-declaration]
   query_available_config();
   ^~~~~~~~~~~~~~~~~~~~~~
browser-main-daemon.c:61:15: warning: unused parameter ‘argc’ [-Wunused-parameter]
 int main (int argc, char *argv[])
               ^~~~
browser-main-daemon.c:61:27: warning: unused parameter ‘argv’ [-Wunused-parameter]
 int main (int argc, char *argv[])
                           ^~~~
browser-main-daemon.c: At top level:
browser-main-daemon.c:110:6: warning: conflicting types for ‘query_available_config’
 void query_available_config(void)
      ^~~~~~~~~~~~~~~~~~~~~~
browser-main-daemon.c:74:3: note: previous implicit declaration of ‘query_available_config’ was here
   query_available_config();
   ^~~~~~~~~~~~~~~~~~~~~~
browser-main-daemon.c: In function ‘query_available_config’:
browser-main-daemon.c:138:14: warning: ‘return’ with a value, in function returning void
       return 1;
              ^
browser-main-daemon.c:110:6: note: declared here
 void query_available_config(void)
      ^~~~~~~~~~~~~~~~~~~~~~
browser-main-daemon.c:146:14: warning: ‘return’ with a value, in function returning void
       return 1;
              ^
browser-main-daemon.c:110:6: note: declared here
 void query_available_config(void)
      ^~~~~~~~~~~~~~~~~~~~~~
browser-main-daemon.c:155:14: warning: ‘return’ with a value, in function returning void
       return 1;
              ^
browser-main-daemon.c:110:6: note: declared here
 void query_available_config(void)
      ^~~~~~~~~~~~~~~~~~~~~~
browser-main-daemon.c:161:14: warning: ‘return’ with a value, in function returning void
       return 1;
              ^
browser-main-daemon.c:110:6: note: declared here
 void query_available_config(void)
      ^~~~~~~~~~~~~~~~~~~~~~
browser-main-daemon.c: In function ‘handle_audio’:
browser-main-daemon.c:207:26: warning: unused parameter ‘nothing’ [-Wunused-parameter]
 void* handle_audio(void* nothing)
                          ^~~~~~~
browser-main-daemon.c: In function ‘handle_connections_control’:
browser-main-daemon.c:385:40: warning: unused parameter ‘nothing’ [-Wunused-parameter]
 void *handle_connections_control(void* nothing)
                                        ^~~~~~~
browser-main-daemon.c: In function ‘handle_connections_audio’:
browser-main-daemon.c:474:38: warning: unused parameter ‘nothing’ [-Wunused-parameter]
 void* handle_connections_audio(void* nothing) {
                                      ^~~~~~~
gcc -g -Wall -Wextra -O0 -std=gnu99 browser-wsaudio.c     -o browser-wsaudio     -lwebsock   -lpthread
browser-wsaudio.c: In function ‘main’:
browser-wsaudio.c:100:19: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘ssize_t {aka long int}’ [-Wformat=]
       printf("%X %d\n", magic_byte, t);
                  ~^
                  %ld
browser-wsaudio.c:188:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (i = 0; i < numChannelConfigs; i++) {
                     ^
browser-wsaudio.c:206:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (i = 0; i < numPossibleRates; i++) {
                     ^
browser-wsaudio.c: In function ‘send_possible_config’:
browser-wsaudio.c:276:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < numChannelConfigs; i++) {
                     ^
browser-wsaudio.c:279:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     else if (i == numChannelConfigs - 1)
                ^~
browser-wsaudio.c:289:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < numPossibleRates; i++) {
                     ^
browser-wsaudio.c:292:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     else if (i == numPossibleRates - 1)
                ^~
browser-wsaudio.c: In function ‘main_ws’:
browser-wsaudio.c:330:21: warning: unused parameter ‘nothing’ [-Wunused-parameter]
 void* main_ws(void* nothing) {
                     ^~~~~~~
In file included from /usr/local/include/websock/websock.h:73:0,
                 from browser-wsaudio.c:5:
browser-wsaudio.c: At top level:
/usr/local/include/websock/utf.h:25:17: warning: inline function ‘decode’ declared but never defined
 uint32_t inline decode(uint32_t *state, uint32_t *codep, uint32_t byte);
                 ^~~~~~
//usr/local/lib/libwebsock.so: undefined reference to `decode'
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'browser-wsaudio' failed
make: *** [browser-wsaudio] Error 1`

I'm using ubuntu 18.04

any ideas? Many thanks in advance

**Comment by fakufaku** [comment]
Hi, have you installed [`libwebsock`](https://github.com/payden/libwebsock) and [`jansson`](http://www.digip.org/jansson/) ?

**Comment by fakufaku** [comment]
So I spent some time trying to debug this. I have the same problem on Ubuntu 18.04 (that has GCC 5 and 7 only), but it worked on Ubuntu 14 with GCC 4.8.4.

Note that the problem is in `libwebsock`, not `easy-dsp`. It might have to do with the fact that the function `decode` (never called directly in `easy-dsp`) is declared as inline, but still included in the symbol table of the shared library. You could try to raise this issue with [the developers there](https://github.com/payden/libwebsock/issues) directly if you really need to use GCC > 4.

**Comment by taospartan** [comment]
many thanks for your quick response, I've solved the issue by recompiling libwebsock with inline removed from utf.c and utf.h.

**Comment by fakufaku** [comment]
Great!
